name: Ruby

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run rubocop
      run: bundle exec rubocop
    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load
      env:
        RAILS_ENV: test
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: postgres
    - name: Run tests
      run: bundle exec rspec spec
      env:
        RAILS_ENV: test
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: postgres